using CliFx;
using CliFx.Binding;
using CliFx.Infrastructure;
using CliWrap;
using Labuladuo.PathExtensions;
using SingBoxLib.Configuration;
using SingBoxLib.Configuration.Inbound;
using SingBoxLib.Configuration.Inbound.Abstract;
using SingBoxLib.Configuration.Outbound;
using SingBoxLib.Configuration.Shared;
using System.Diagnostics;
using System.Text;
using TjslpNetworkTunnelDeployer.Extensions;


namespace TjslpNetworkTunnelDeployer.Commands;


[Command("deploy", Description = "Deploy the tunnels.")]
partial class DeployCommand : ICommand
{
    [CommandOption("configuration", 'c', 
        Description = "Path of the configuration file. It can be generated by generate-configuration command.")]
    public required string Configuration { get; set; }

    [CommandOption("directory", 'd', Description = "The directory for outputs, logs and sing-box working directories.")]
    public required string Directory { get; set; }

    private async Task<CommandTask<CommandResult>> BeginSingboxAsync(
        StreamWriter tunnelStartupLog,
        DirectoryInfo tunnelLogDirectory,
        DeployConfiguration.LocalToolConfiguration localTools,
        DeployConfiguration.TunnelConfiguration tunnel)
    {
        await tunnelStartupLog.WriteLineAsync($"Generating sing-box configuration...");
        var singBoxConfiguration = new SingBoxConfig()
        {
            Inbounds = new List<InboundConfig>()
            {
                new MixedInbound()
                {
                    Listen = "127.0.0.1",
                    ListenPort = tunnel.SingBox.Port,
                    Users = new List<ProxyUser>()
                    {
                        new ProxyUser()
                        {
                            Username = tunnel.SingBox.Username,
                            Password = tunnel.SingBox.Password
                        }
                    }
                }
            }
        };
        var logDirectory = tunnelLogDirectory.CreateSubdirectory("local-sing-box");
        var configurationFile = logDirectory.GetFileInfo("config.json");
        await tunnelStartupLog.WriteLineAsync($"Path: {configurationFile}");
        await File.WriteAllTextAsync(configurationFile.FullName, singBoxConfiguration.ToJsonPretty());
        await tunnelStartupLog.WriteLineAsync($"Completed.");

        await tunnelStartupLog.WriteLineAsync($"Starting sing-box...");
        var command = new StartProcessConfiguration(
            Environment.ProcessId,
            localTools.SingBox,
            [
                "run",
                "-c", configurationFile.FullName,
                "-D", logDirectory.CreateSubdirectory("working-directory").FullName
            ],
            "",
            logDirectory.GetFileInfo("sing-box.out.txt").FullName,
            logDirectory.GetFileInfo("sing-box.err.txt").FullName
        ).PrepareToRunStartProcessInNewProcess(
            logDirectory.GetFileInfo("sing-box-watch.out.txt").FullName,
            logDirectory.GetFileInfo("sing-box-watch.err.txt").FullName
        );
        await tunnelStartupLog.WriteLineAsync($"Command: {command}");
        var result = command.ExecuteAsync();
        await tunnelStartupLog.WriteLineAsync("Completed.");
        return result;
    }

    private async Task<CommandTask<CommandResult>> BeginSshAsync(
        StreamWriter tunnelStartupLog,
        DirectoryInfo tunnelLogDirectory,
        DeployConfiguration.LocalToolConfiguration localTools,
        DeployConfiguration.TunnelConfiguration tunnel)
    {
        await tunnelStartupLog.WriteLineAsync($"Starting ssh...");

        var logDirectory = tunnelLogDirectory.CreateSubdirectory("ssh");
        var remoteSingBoxConfig = new SingBoxConfig()
        {
            Inbounds =
            [
                new DirectInbound
                {
                    Listen = "0.0.0.0",
                    ListenPort = tunnel.Forward.PortLan,
                    OverrideAddress = "127.0.0.1",
                    OverridePort = tunnel.Forward.PortLocal,
                }
            ]
        };

        var remoteScript =
            $"""
            SING_BOX_WORKING_DIRECTORY="$(mktemp -d -t XXXXXXXXXXXXXXXXXXXX)"
            echo "{remoteSingBoxConfig.ToBase64()}" | base64 -d > "$SING_BOX_WORKING_DIRECTORY/config.json"
            trap 'rm -rf "$SING_BOX_WORKING_DIRECTORY"; kill 0' EXIT
            "{tunnel.Tools.SingBox}" run -D "$SING_BOX_WORKING_DIRECTORY"
            """.ReplaceLineEndings("\n");
        var remoteScriptBase64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(remoteScript));
        var command = new StartProcessConfiguration(
            Environment.ProcessId,
            localTools.Ssh,
            [
                "-tt",
                "-o", "ExitOnForwardFailure=yes",
                "-o", "ServerAliveInterval=60",
                "-o", "ServerAliveCountMax=3",
                "-p", $"{tunnel.Ssh.Port}",
                $"{tunnel.Ssh.User}@{tunnel.Ssh.Host}",
                "-R", $"{tunnel.Forward.PortLocal}:127.0.0.1:{tunnel.SingBox.Port}",
                $"bash -c \"echo {remoteScriptBase64} | base64 -d | bash\""
            ],
            "",
            logDirectory.GetFileInfo("ssh.out.txt").FullName,
            logDirectory.GetFileInfo("ssh.err.txt").FullName
        ).PrepareToRunStartProcessInNewProcess(
            logDirectory.GetFileInfo("ssh-watch.out.txt").FullName,
            logDirectory.GetFileInfo("ssh-watch.err.txt").FullName
        );
        await tunnelStartupLog.WriteLineAsync($"Command: {command}");
        var result = command.ExecuteAsync();
        await tunnelStartupLog.WriteLineAsync("Completed.");
        return result;
    }

    public async ValueTask ExecuteAsync(IConsole console)
    {
        var directory = System.IO.Directory.CreateDirectory(this.Directory);

        console.WriteLine("Loading configurations...");
        var configuration = DeployConfiguration.Deserialize(
            await File.ReadAllTextAsync(this.Configuration));
        Trace.Assert(configuration is not null);
        console.WriteLine("Completed.");

        foreach (var (tunnelIndex, tunnel) in configuration.Tunnels.Index())
        {
            console.WriteLine($"Starting tunnel {tunnelIndex} / {configuration.Tunnels.Count}...");
            
            var tunnelDirectory = directory.CreateSubdirectory($"tunnel-{tunnelIndex}");
            using var tunnelStartupLog = new StreamWriter(Path.Join(tunnelDirectory.FullName, "startup.log.txt"))
            {
                AutoFlush = true
            };
            try
            {
                _ = await BeginSingboxAsync(tunnelStartupLog, tunnelDirectory, configuration.Tools, tunnel);
                _ = await BeginSshAsync(tunnelStartupLog, tunnelDirectory, configuration.Tools, tunnel);
            }
            catch (Exception ex)
            {
                await tunnelStartupLog.WriteLineAsync($"{ex}");
            }
            console.WriteLine($"Completed.");
        }

        console.WriteLine("Generating outbounds configurations for remote use...");
        var remoteOutboundsConfiguration = new SingBoxConfig()
        {
            Outbounds = [.. configuration.Tunnels.Select(x => new SocksOutbound(
                $"{x.SingBox.Username}-{x.Ssh.Host}-{x.Forward.PortLan}")
                {
                    Server = x.Ssh.Host,
                    ServerPort = x.Forward.PortLan,
                    Username = x.SingBox.Username,
                    Password = x.SingBox.Password
                })
            ]
        };

        var outboundsConfiguration = directory.Combine("outbounds.json");
        console.WriteLine($"Path: {outboundsConfiguration}");
        await File.WriteAllTextAsync(outboundsConfiguration.FullName, remoteOutboundsConfiguration.ToJsonPretty());
        console.WriteLine($"Completed.");

        console.WriteLine($"Press Ctrl+C to stop the services.");
        await Task.Delay(Timeout.Infinite);
    }
}
